### ISSUE TITLE
코드로 메뉴 검색

### ISSUE THREAD

**Issue by crushed-taro** [JPA-REACT-TEAM/git-collaborate#2]
# 기능 추가 요청

## 기능 설명
코드로 메뉴를 검색

## 기대하는 효과
코드를 가지고 메뉴를 검색할 수 있다.

## 구현 가능성
기능은 구현 가능. JPA를 통해 구현할 수 있다.

## TO-DO
- [ ] MenuController.java 기능 추가.
- [ ] MenuService.java 기능 추가.
- [ ] MenuRopository.interface 기능 추가 및 오버라이딩
